/*
Формат файла - json
Поддержка Etag включена по умолчанию, если сервер поддерживает Etag, то скачивание будет произведено только если файл изменился
В ручном режиме Etag не посылается серверу, но обновляется после получения заголовков

log_level - задает уровень логирования. debug/notice/info/warning/error
log_path - задает путь и имя лога. Если не указан то будет использоваться каталог где находится
sources - список обрабатываемых источников
id - уникальный идентификатор источника. Будет использован для создания каталога.
url - ссылка на xmltv
keep_source - необязательный. Если задан в true, то сохраняет оригинальный скачанный файл.
manual_check - необязательный. Задает время следующего скачивания файла в часах. Необходим если сервер не поддерживает Etag, а проверка делается часто.
*/

{
    "log_level": "debug",
    "log_path": "/tmp/epg/converter.log",
    "sources": [
        {"id":"bcu", "manual_check": 48, "url": "https://bcumedia.pro/epg.xml.gz"},
        {"id":"edem", "keep_source": true, "url": "http://epg.one/epg.xml.gz"},
        {"id":"iptv", "url": "http://iptv-content.rv77.pw/guide.xml"}
    ]
}
