[
  {"id":"bcu", "manual_check": 48, "url": "https://bcumedia.pro/epg.xml.gz"},
  {"id":"edem", "keep_source": true, "purge_stalled": 14, "url": "http://epg.one/epg.xml.gz"},
  {"id":"iptv", "url": "http://iptv-content.rv77.pw/guide.xml"}
]
